name: Metrics
on:
  schedule: [{cron: "0 0 */7 * *"}]
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.MATRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_sponsorships: yes
          plugin_sponsorships_sections: sponsorships
          plugin_sponsorships_size: 64
